CREATE DATABASE projectmart;

USE projectmart;

CREATE TABLE users (
  id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  firstname VARCHAR(50) NOT NULL,
  lastname VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  phone NUMERIC(10,0) NOT NULL,
  dateofbirth DATE NOT NULL,
  address VARCHAR(60) NOT NULL
);